/** Declaration file generated by dts-gen */


declare module 'animation-frame' {
    export default class AnimationFrame {
        constructor(options: {}|number|null);

        cancel(id: number): void;

        request(callback: (time: any) => void): number;

        static FRAME_RATE: number;

        static shim(options: Object|Number): AnimationFrame;
    }

}


